import src.PyMathPlot as plot

#plot.draw_line_using_matlib()
#plot.draw_line_using_givenaxis_value()
#plot.draw_line_byreadingfrom_textfile()
#plot.chart_for_financial_data()
#plot.plot_moreline()
#plot.plot_line_with_marker()
#plot.plot_quantities()
#plot.plot_line_with_diff_format()
#plot.multiple_type_chart()
#plot.creating_multiple_plot()
#plot.draw_bar_graph()
#plot.bar_graph_with_different_color()
#plot.draw_pie_chart()
plot.pie_chart_for_country()