import src.PythonIOProblem as PY_IO

PY_IO.readingfile('textfile.txt')
#PY_IO.readingnlinesfromfile('textfile.txt')
#PY_IO.appendingtextinexistingfile('textfile.txt')
#PY_IO.tail('textfile.txt')
#PY_IO.readingfromfileandstoringinlist('textfile.txt')
#PY_IO.readingfromfileandstoringinarray('textfile.txt')
#PY_IO.longestwordinfile('textfile.txt')
#PY_IO.number_of_lines_in_file('textfile.txt')
#PY_IO.frequency_of_word('textfile.txt')
#PY_IO.file_size('textfile.txt')
#PY_IO.writing_list_in_file()
#PY_IO.copycontent_from_file()
#PY_IO.combine_from_onefileto_other()
PY_IO.reading_randomline('textfile.txt')
PY_IO.is_file_closed('textfile.txt')