import src.PythonBasics as PY

pb = PY.PythonBasic()

pb.getversion()
pb.currentdateandtime()

#pb.areaofcircle()
#pb.reverseuserinput()

#pb.inputastupleandlist()
#pb.extentionoffile()
#pb.gettingfirstandlastcolor()
#pb.examinationschedule()
#pb.acceptinteger()
#pb.printdocument()
#pb.printcalendar()
#pb.differencebtwdate()
#pb.volumeofsphere()
#pb.returndifference()
#pb.sumofthreenumber()
#pb.addingisbeforestring()
#pb.copyofstring()
#pb.findingevenandodd()
#pb.counting4inlist()
#pb.ncopyoffirsttwochar()
#pb.isvowel()
#pb.isdatapresent()
#pb.generatinghistogram()
#pb.concatetheelementoflist()
#pb.printallevennumber()
#pb.listdifference()
#pb.areaoftriangle()
#pb.gcdoftwonumber()
pb.lcmoftwonumber()